# Generated by Django 4.0.6 on 2022-07-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_client', models.CharField(max_length=50, verbose_name='ФИО')),
                ('sex_client', models.CharField(max_length=1, verbose_name='Пол(м/ж)')),
                ('numbers_phone', models.IntegerField(max_length=11, verbose_name='Номер телефона(начиная с 8)')),
                ('adress_client', models.CharField(max_length=150, verbose_name='Адрес')),
                ('car_client', models.IntegerField(max_length=2, verbose_name='Количество втомобилей на парковке')),
            ],
        ),
    ]
