# Generated by Django 4.0.6 on 2022-08-04 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('sex', models.CharField(max_length=1, verbose_name='Пол(м/ж)')),
                ('numbers_phone', models.CharField(max_length=11, verbose_name='Номер тел.(с 8)')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('cars', models.IntegerField(verbose_name='Кол-во авто')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.TextField(verbose_name='Марка')),
                ('model', models.TextField(verbose_name='Модель')),
                ('color', models.TextField(verbose_name='Цвет')),
                ('licence_plate', models.TextField(verbose_name='Гос номер')),
                ('is_on_parking', models.BooleanField(unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
