# Generated by Django 4.0.6 on 2022-07-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.RenameField(
            model_name='client',
            old_name='adress_client',
            new_name='address_client',
        ),
        migrations.AlterField(
            model_name='client',
            name='car_client',
            field=models.IntegerField(max_length=2, verbose_name='Кол-во авто'),
        ),
        migrations.AlterField(
            model_name='client',
            name='numbers_phone',
            field=models.CharField(max_length=11, verbose_name='Номер тел.(с 8)'),
        ),
    ]
