# Generated by Django 4.0.6 on 2022-08-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sex',
            field=models.CharField(choices=[('м', 'мужской'), ('ж', 'женский')], max_length=1),
        ),
    ]
