# Generated by Django 4.0.6 on 2022-08-19 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Имя не может быть меньше 3х символов')], verbose_name='ФИО'),
        ),
    ]
