# Generated by Django 4.0.6 on 2022-08-04 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_client_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='is_on_parking',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='licence_plate',
            field=models.TextField(unique=True, verbose_name='Гос номер'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(3, message='Имя не может быть меньше 3х символов')], verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='client',
            name='numbers_phone',
            field=models.TextField(unique=True, verbose_name='Номер тел.(с 8)'),
        ),
    ]
