# Generated by Django 4.0.6 on 2022-07-17 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='car_client',
            field=models.IntegerField(verbose_name='Кол-во авто'),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=1, verbose_name='Модель')),
                ('color', models.CharField(max_length=11, verbose_name='Цвет')),
                ('gos_number', models.CharField(max_length=150, verbose_name='Гос номер')),
                ('flag', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
